foreground {{colors.on_surface.dark.hex}}
background {{colors.surface.dark.hex}}

selection_foreground {{colors.on_primary.dark.hex}}
selection_background {{colors.primary.dark.hex}}

cursor {{colors.primary.dark.hex}}
cursor_text_color {{colors.on_primary.dark.hex}}

color0 {{colors.surface_container.dark.hex}}
color1 {{colors.error.dark.hex}}
color2 {{colors.tertiary.dark.hex}}
color3 {{colors.secondary.dark.hex}}
color4 {{colors.primary.dark.hex}}
color5 {{colors.secondary.dark.hex}}
color6 {{colors.tertiary.dark.hex}}
color7 {{colors.on_surface.dark.hex}}

color8 {{colors.surface_container_highest.dark.hex}}
color9 {{colors.error.dark.hex}}
color10 {{colors.tertiary_fixed.dark.hex}}
color11 {{colors.secondary_fixed.dark.hex}}
color12 {{colors.primary_fixed.dark.hex}}
color13 {{colors.secondary_fixed_dim.dark.hex}}
color14 {{colors.tertiary_fixed_dim.dark.hex}}
color15 {{colors.surface_bright.dark.hex}}
